# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on: push

permissions: write-all

jobs:
  deploy-windows:

    runs-on: [self-hosted, windows, preconfigured]

    steps:
    - uses: actions/checkout@v3
    - name: Build package
      run: tox
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        
  deploy-linux:
    runs-on: [self-hosted preconfigured Linux]
    steps:
    - uses: actions/checkout@v3
    - name: Build package
      run: tox
    - name: Audit Packages
      run: pip install auditwheel && python util.py
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
